# Generated by Django 3.2.7 on 2021-11-20 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seguidores',
        ),
    ]
