# Generated by Django 3.2.7 on 2021-11-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
