# Generated by Django 3.2.7 on 2021-11-20 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_seguidores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguidores',
            name='followerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='seguidores',
            name='user',
            field=models.IntegerField(),
        ),
    ]
