# Generated by Django 3.2.7 on 2021-11-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211120_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguidores',
            name='followerid',
        ),
        migrations.AddField(
            model_name='seguidores',
            name='followerid',
            field=models.ManyToManyField(to='user.User'),
        ),
    ]
