# Generated by Django 3.2.7 on 2021-11-20 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20211120_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguidores',
            name='followerid',
        ),
        migrations.AddField(
            model_name='seguidores',
            name='followerid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
