# Generated by Django 3.2.7 on 2021-11-21 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20211120_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('followedid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
