# Generated by Django 3.2.7 on 2021-11-21 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_seguidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguidos',
            name='followedid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seguidos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
