# Generated by Django 3.2.7 on 2021-11-21 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20211121_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguidos',
            name='user',
        ),
        migrations.AddField(
            model_name='seguidos',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seguidos',
            name='followedid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
